data:
  original_data:
    root_path: "./data/original_food_intake_data"
    category_num: 11
    person_num_per_category: 10
  generated_data:
    save_path: "./data"

post_models:
  resnet:
  cross_vit:
    embed_dim: 32
    num_heads: 2
    num_layers: 2
    mlp_dim: 32
    dropout: 0.1

train:
  dataset:
    sample_length: 512
    stride: 128
    cross_person: False
    train_person_num: 8
    train_ratio: 0.8
  pre_model:
    base_c_watch: 32
    base_c_glasses: 16
    num_epochs: 50
    learning_rate: 0.003
    mask_percentage: 0.75
    patience: 5
    data_loader:
      batch_size: 32
      shuffle: True
      num_workers: 4
  post_model:
    model_name: "CrossVit"
    num_epochs: 15
    learning_rate: 0.001
    patience: 5
    # use for train the post model or deploy test the whole model
    data_loader:
      batch_size: 16
      shuffle: True
      num_workers: 4
  # logging_mode: "console" or "tensorboard" or "file"
  logging_mode: "file"

deploy:
  pre_model:
    train_id: "2023_11_22_15_40_48"
    base_c_watch: 32
    base_c_glasses: 16
    mask_percentage: 0.75
    threshold: 31.442
  post_model:
    train_id: "2023_11_22_16_24_01"