data:
  original_data:
    root_path: "./data/original_food_intake_data"
    category_num: 11
    person_num_per_category: 10
  generated_data:
    save_path: "./data"

train:
  dataset:
    sample_length: 512
    stride: 128
    cross_person: False
    train_person_num: 8
    train_ratio: 0.8
  pre_model:
    basc_c_watch: 2
    basc_c_glasses: 2
    num_epochs: 30
    learning_rate: 0.0001
    mask_percentage: 0.8
    patience: 20
    data_loader:
      batch_size: 16
      shuffle: True
      num_workers: 4
  post_model:
    num_epochs: 30
    learning_rate: 0.0001
    patience: 20
    data_loader:
      batch_size: 16
      shuffle: True
      num_workers: 4
  # logging_mode: "console" or "tensorboard" or "file"
  logging_mode: "file"

deploy:
  pre_model:
    train_id:
    basc_c_watch: 2
    basc_c_glasses: 2
    mask_percentage: 0.8
    threshold:
  post_model:
    train_id: